config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home', to: 'posts#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :posts, only: %i[new create destroy]
  get 'explore', to: 'posts#search'
  get ':unique_id/status/:id', to: 'posts#show'
  
  get 'settings/profile', to: 'users#edit'

  resources :comments, only: %i[create destroy]
  resources :users, only: %i[update destroy]
  resources :relationships, only: %i[create destroy]
  resources :likes, only: %i[create destroy]

  get ':unique_id', to: 'users#show'
  get ':unique_id/following', to: 'users#following'
  get ':unique_id/followers', to: 'users#followers'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :string(255)
#  user_id    :integer
#  image      :string(255)
#  evaluation :float(24)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :delete_all
  has_many :post_tag_relations, dependent: :delete_all
  has_many :tags, through: :post_tag_relations
  has_many :likes, dependent: :delete_all

  validates :body, presence: true, length: { maximum: 255 }
  validates :user_id, presence: true

  # has_one_attached :image
  mount_uploader :image, ImageUploader

  def self.search(search)
    return all unless search
    where(['body like ?', "%#{search}%"])
  end

  def like(user)
    likes.create(user_id: user.id)
  end

  def unlike(user)
    likes.find_by(user_id: user.id).destroy
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_target_post, only: [:show, :destroy]

  def index

  end

  def search
    if params[:search].blank? == false || params[:tag_id].blank? == false
      @search_params = true
    else
      @search_params = false
    end
    # TODO:検索していないときは、最新の20件
    if @search_params
      @search_posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
      @search_posts = @search_posts.search(params[:search])
      @search_posts = @search_posts.order(created_at: :desc).page(params[:page])
      @search_users = User.all.search_user(params[:search])
    else
      @search_posts = Post.all
      @search_posts = @search_posts.order(created_at: :desc).limit(20).page(params[:page])
    end
  end

  def new
    @post = Post.new
  end

  def create 
    post = Post.new(post_params)
    if post.save 
      flash[:notice] = "投稿しました。"
      redirect_to home_path
    else
      redirect_to new_post_path, flash: {
        post: post,
        error_messages: post.errors.full_messages
      }
    end
  end

  def show
    @comment = Comment.new(post_id: @post.id)
  end

  def destroy
    @post.destroy
    redirect_to home_path, flash: { notice: "投稿を削除しました。" }
  end

  private
  def post_params
    params.require(:post).permit(:body, :user_id,:evaluation, :image, tag_ids: [])
  end

  def set_target_post
    @post = Post.find(params[:id])
  end
end

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
  <div>
    <%= link_to 'キャンセル', :back %>
    <%= f.submit '投稿する', class: 'btn-tweet' %>
  </div>
  
  <%= f.hidden_field :user_id, id: 'post-user' , value: current_user.id %>
  <div class="form-group">
    <%= f.text_area :body, rows: 10, class: 'form-control' %>
  </div>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <div class="form-group">
    <span>タグ</span>
    <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
      <div class="form-check">
        <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
        <% end %>
      </div>
    <% end %>
  </div>
  <span></span>
  <%= f.hidden_field :evaluation, id:"evaluation_value", class: 'form-control' %>
<% end %>
<div>
  おすすめ度：
  <%= button_tag "", id:"evaluation_1", class:"far fa-star", onclick:"ChangeEvaluation(1)" %>
  <%= button_tag "", id:"evaluation_2", class:"far fa-star", onclick:"ChangeEvaluation(2)" %>
  <%= button_tag "", id:"evaluation_3", class:"far fa-star", onclick:"ChangeEvaluation(3)" %>
  <%= button_tag "", id:"evaluation_4", class:"far fa-star", onclick:"ChangeEvaluation(4)" %>
  <%= button_tag "", id:"evaluation_5", class:"far fa-star", onclick:"ChangeEvaluation(5)" %>
</div>

<script>
  function ChangeEvaluation(num) {
    $("#evaluation_value").val(num);
    for (var i=1; i<=5; i++) {
      $("#evaluation_" + i).removeClass("fas fa-star");
      $("#evaluation_" + i).addClass("far fa-star");
    }

    for (var i=1; i<=num; i++) {
      $("#evaluation_" + i).removeClass("far fa-star");
      $("#evaluation_" + i).addClass("fas fa-star");
    }
  }
</script>

app/views/posts/_post.html.erb
<div class="card">
  <div class="card-header">
    <%= link_to "../" do %>
      <div class="icon-post-field">
          <% if post.user.image? %>
              <%= image_tag post.user.image.to_s, class:'icon-user-inner' %>
          <% else %>
              <%= image_tag 'unknown.png', class:'icon-user-inner' %>
          <% end %>
      </div>
      <div style="float:left;">
        <p class="user-name"><%= post.user.name %></p> 
        <p class="gray">@<%= post.user.unique_id %></p>
      </div>
      <% if current_user?(post.user) %>
        <%= link_to '削除', post, class:"post-delete", method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
      <% end %>
    <% end %>
  </div>
  <div class="card-body", style="margin-top:-1.2rem">
    <% post.tags.each do |tag| %>
      <span class="badge badge-primary"><%= tag.name %></span>
    <% end %>
    <p class="card-text"><%= simple_format(post.body) %></p>
    <% if post.evaluation.nil? == false %>
      おすすめ度：
      <i id="evaluation_1", class="far fa-star"></i>
      <i id="evaluation_2", class="far fa-star"></i>
      <i id="evaluation_3", class="far fa-star"></i>
      <i id="evaluation_4", class="far fa-star"></i>
      <i id="evaluation_5", class="far fa-star"></i>
    <% end %>
  </div>
  <% if post.image? %>
    <%= image_tag post.image.to_s %>
  <% end %>



  <div class="post-show-date">
    <%= GetDateFormat(post.created_at) %>
  </div>
  <%# TODO:buttonの枠線を消したい。linkにするとsubmitが効かなくなる。 %>
  <div>
    <% if post.likes.find_by(user_id: current_user.id).nil? %>
      <%= link_to likes_path(post_id: post.id), class:"heart", remote: true, method: :post do %>
        <i class="far fa-heart"></i>
      <% end %>
    <% else %>
      <%= link_to like_path(post_id: post.id), class:"heart", remote: true, method: :delete do %>
        <i class="fas fa-heart" style="color:pink"></i>
      <% end %>
    <% end %>
     <%= post.likes.count %>
  </div>
</div>

<script>
  for (var i=1; i<=<%= post.evaluation %>; i++) {
    $("#evaluation_" + i).removeClass("far fa-star");
    $("#evaluation_" + i).addClass("fas fa-star");
  }
</script>

app/views/posts/_posts.html.erb
<% if posts.length >= 1 %>
  <% posts.each do |post| %>
    <div class="card", style="padding-top:0.3rem">
      <div class="user-field">
        <%= link_to "./#{post.user.unique_id.to_s}" do %>
          <div class="icon-post-field">
            <% if post.user.image? %>
              <%= image_tag post.user.image.to_s, class:'icon-user-inner' %>
            <% else %>
              <%= image_tag 'unknown.png', class:'icon-user-inner' %>
            <% end %>
          </div>
          <div style="float:left;">
            <p class="user-name"><%= post.user.name %></p> 
            <p class="gray">@<%= post.user.unique_id %></p>
          </div>
        <% end %>
      </div>
      <%= link_to "/#{post.user.unique_id.to_s}/status/#{post.id}" do %>
        <div style="margin-top:-10px;">
          <% post.tags.each do |tag| %>
            <p class="badge badge-primary"><%= tag.name %></p>
          <% end %>
          <p><%= post.body %></p>
          <% if post.evaluation.nil? == false %>
            おすすめ度：
            <% post.evaluation.to_i.times do |i| %>
              <i class="fas fa-star"></i>
            <% end %>
            <% (5 - post.evaluation.to_i).times do |j| %>
              <i class="far fa-star"></i>
            <% end %>
          <% end %>
        </div>
        <%# TODO: 比率は維持したまま、表示サイズの上限を設ける %>
        <% if post.image? %>
          <div class="post-image">
            <%= image_tag post.image.to_s %>
          </div>
        <% end %>

        <div class="post-index-comment" style="margin-top:10px;">
          <% if post.likes.find_by(user_id: current_user.id).nil? %>
            <i class="far fa-heart"></i> <%= post.likes.count %>
          <% else %>
            <i class="fas fa-heart" style="color:pink"></i> <%= post.likes.count %>
          <% end %> 
          　<i class="far fa-comment"></i> <%= post.comments.count %>
        </div>
        <p class="post-date"><%= GetDateFormat(post.created_at) %></p>
      <% end %>
    </div>
  <% end %>
  <%= paginate posts %>
<% else %>
  <p style="padding: 0 15px;">投稿がありません。</p>
<% end %>

app/views/posts/_search_users.html.erb
<% if users.nil? == false && users.length >= 1 %>
  <p style="margin-bottom:0;">アカウント</p>
  <div class="user-list">
    <% users.each do |user| %>
      <%= link_to "./#{user.unique_id.to_s}" do %>
        <div class="user-card">
          <div class="icon-post-field" style="float:left;">
            <% if user.image? %>
              <%= image_tag user.image.to_s, class:'icon-user-inner' %>
            <% else %>
              <%= image_tag 'unknown.png', class:'icon-user-inner' %>
            <% end %>
            </div>
            <div class="user-detail">
              <p style="color:black; font-weight:bold; margin-bottom:0;"><%= user.name %></p>
              <p style="color:grey;">@<%= user.unique_id %></p>
              <p style="color:black;"><%= user.introduction %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container--sm bottom-space">
  <%= render partial: 'posts/posts', locals: { posts: @following_posts } %>
  <%= link_to (content_tag(:i, '', class:"fas fa-plus-circle", style:"font-size:50px")), new_post_path, class:"btn-add-tweet" %>
</div>

app/views/posts/new.html.erb
<div class="container bottom-space">
  <h2>新規投稿</h2>
  <%= render "shared/error_messages" %>
  <%= render partial:'form', locals: { post: @post } %>
</div>

app/views/posts/search.html.erb
<div class="container--sm bottom-space">
  <div class="d-flex align-items-center" style="margin: 5px 15px">
  <%# TODO:placeholderに虫眼鏡アイコンを表示する %>
    <%= form_tag(explore_path,:method => 'get') do %>
      <%= text_field_tag :search, params[:search], class:"searchBox font-awesome fa", placeholder:"検索" %>
      <%= submit_tag '検索', :name => nil, style:"display:none;" %>
      <%= select_tag :tag_id,
        options_from_collection_for_select(Tag.all, :id, :name, params[:tag_id]),
        {
          prompt: 'タグで絞り込み',
          class: 'form-control boards__select',
          style:'margin-left: 4px;',
          onchange: 'submit(this.form);'
        }
      %>
    <% end %>
  </div>

  <p style="margin-bottom:0;">アカウント</p>
  <%= render partial: 'users/users', locals: { users: @search_users } %>
  <div class="both">
    <%= render partial: 'posts/posts', locals: { posts: @search_posts } %>
  </div>
  <%= link_to (content_tag(:i, '', class:"fas fa-plus-circle", style:"font-size:50px")), new_post_path, class:"btn-add-tweet" %>
</div>

app/views/posts/show.html.erb
<div class="container bottom-space">
  <%= render @post %>
  <% if @post.comments.count > 0 %>
    <div class="p-comment__list">
      <div class="p-comment__listTitle">コメント</div>
      <%= render @post.comments %>
    </div>
  <% end %>
  
  <%= render partial: 'comments/form', locals: { comment: @comment } %>
</div>